### ISSUE TITLE
For yesterday, `confidence` reduces a lot.

### ISSUE THREAD

**Issue by aliokan** [OpenCageData/opencagedata-misc-docs#7]
I mainly use opencagedata to get location from countries and zip_code in Europe. 
Since yesterday, we notice confidence result decrease strongly, I don’t know if that change is made on purpose. 

https://api.opencagedata.com/geocode/v1/json?countrycode=LU&q=8530&language=native&add_request=1&limit=1&key=***&pretty=1
before: `confidence:9`
today:`confidence:4`

https://api.opencagedata.com/geocode/v1/json?countrycode=FR&q=33260&language=native&add_request=1&limit=1&key=***&pretty=1
before: `confidence:9`
today:`confidence:3`

https://api.opencagedata.com/geocode/v1/json?countrycode=FR&q=73440&language=native&add_request=1&limit=1&key=***&pretty=1
before: `confidence:9`
today:`confidence:4`

I got bad confidence for these requests: 
- 93300, FR
- 8508, LU
- 69003, FR
- 33260, FR
- 73440, FR
- 2536, CH

**Comment by freyfogle** [comment]
Hi, thanks for letting us know, and specific example 

Please can you email us at support@opencagedata.com that is a better place for support issues 
or use https://opencagedata.com/contact

One point though, it is important to know that confidence does not imply correctness, please see:
https://opencagedata.com/api#confidence

Basically Nominatim has changed how postcode areas are defined, they have become larger.

But happy to go into more detail by email.
